### PR TITLE
Change compilation settings to only do x86 and hide unnecessary COM object

### PR DESCRIPTION
**Pull request by danielcaldwell**
Changed project settings to compile for x86 only, also removed the com
visibility of OGRAddLayerDialog as it's not a com object.

### CODE REVIEW

**Comment by rburhum** [comment]
yeah. you can see it under Files Changed. Thanks man!

**Comment by danielcaldwell** [comment]
Sounds good, I must have earned at least 1 karma point for this... lemme
know if you want my help with anything else...

**Comment by rburhum** [comment]
Yup man! Well, according to the latest SP1 release notes (NIM083294 from http://downloads.esri.com/support/downloads/other_/ArcGIS101sp1-issues.htm) There is write support now. http://resources.arcgis.com/en/help/arcobjects-net/componenthelp/index.html#/IsReadOnly_Property/00250000068v000000/ but the docs have not been updated. If you ever feel bored, you could implement write support hahaha. Or not. Thanks anyway man

**Comment by danielcaldwell** [comment]
So with Open Source Projects like these, what do you do to support 10.1 and
10.1 sp1? Do you only support SP1 and tell everyone to upgrade? Or do you
fork or something?

**Comment by rburhum** [comment]
It's your choice. I would basically create a branch and leave the read-only support for 10.x+ and trunk would move to SP1 with write support. If really needed, we always have the ability to  port patches to the previous branch. And with git, it is relatively easy

**Comment by danielcaldwell** [comment]
I don't see any additional methods. Is there a interface I'm missing? Maybe
they didn't reship the interop or something? Not sure.

On Tue, Nov 6, 2012 at 11:26 AM, Ragi Yaser Burhum <notifications@github.com

**Comment by rburhum** [comment]
I had an e-mail exchange with Brent. He told me to implement ITable and ITableWrite

**Pull request merged**
